apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-storage
  namespace: invoiceninja
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-mariadb-data
  namespace: invoiceninja
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
