apiVersion: v1
kind: Service
metadata:
  name: twenty
  namespace: twenty
  labels:
    app.kubernetes.io/name: twenty
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: twenty
  ports:
    - name: http
      port: 3000
      targetPort: http
